export const thumbnailCategories = [
  {
    id: "gaming",
    title: "Gaming",
    cover: "/portfolio/thumbnails/Gaming/1.jpg",
    images: [
      "/portfolio/thumbnails/Gaming/1.jpg",
      "/portfolio/thumbnails/Gaming/2.jpg",
      "/portfolio/thumbnails/Gaming/3.jpg",
      "/portfolio/thumbnails/Gaming/4.jpg",
      "/portfolio/thumbnails/Gaming/5.jpg",
      "/portfolio/thumbnails/Gaming/6.jpg",
      "/portfolio/thumbnails/Gaming/7.jpg",
      "/portfolio/thumbnails/Gaming/8.jpg",
      "/portfolio/thumbnails/Gaming/9.jpg",
      "/portfolio/thumbnails/Gaming/10.jpg",
      "/portfolio/thumbnails/Gaming/11.jpg",
      "/portfolio/thumbnails/Gaming/12.jpg",
      "/portfolio/thumbnails/Gaming/13.jpg",
      "/portfolio/thumbnails/Gaming/14.jpg",
      "/portfolio/thumbnails/Gaming/15.jpg",
      "/portfolio/thumbnails/Gaming/16.jpg",
      "/portfolio/thumbnails/Gaming/17.jpg",
      "/portfolio/thumbnails/Gaming/18.jpg",
      "/portfolio/thumbnails/Gaming/19.jpg",
      "/portfolio/thumbnails/Gaming/20.jpg",
    ],
  },

  {
    id: "business",
    title: "Business",
    cover: "/portfolio/thumbnails/Business/1.jpg",
    images: [
      "/portfolio/thumbnails/Business/1.jpg",
      "/portfolio/thumbnails/Business/2.jpg",
      "/portfolio/thumbnails/Business/3.jpg",
      "/portfolio/thumbnails/Business/4.jpg",
      "/portfolio/thumbnails/Business/5.jpg",
      "/portfolio/thumbnails/Business/6.jpg",
      "/portfolio/thumbnails/Business/7.jpg",
      "/portfolio/thumbnails/Business/8.jpg",
      "/portfolio/thumbnails/Business/9.jpg",
      "/portfolio/thumbnails/Business/10.jpg",
      "/portfolio/thumbnails/Business/11.jpg",
      "/portfolio/thumbnails/Business/12.jpg",
      "/portfolio/thumbnails/Business/13.jpg",
      "/portfolio/thumbnails/Business/14.jpg",
      "/portfolio/thumbnails/Business/15.jpg",
      "/portfolio/thumbnails/Business/16.jpg",
      "/portfolio/thumbnails/Business/17.jpg",
      "/portfolio/thumbnails/Business/18.jpg",
      "/portfolio/thumbnails/Business/19.jpg",
      "/portfolio/thumbnails/Business/20.jpg",
      "/portfolio/thumbnails/Business/21.jpg",
      "/portfolio/thumbnails/Business/22.jpg",
      "/portfolio/thumbnails/Business/23.jpg",
      "/portfolio/thumbnails/Business/24.jpg",
      "/portfolio/thumbnails/Business/25.jpg",
      "/portfolio/thumbnails/Business/26.jpg",
      "/portfolio/thumbnails/Business/27.jpg",
      "/portfolio/thumbnails/Business/28.jpg",
      "/portfolio/thumbnails/Business/29.jpg",
      "/portfolio/thumbnails/Business/30.jpg",
      "/portfolio/thumbnails/Business/31.jpg",
      "/portfolio/thumbnails/Business/32.jpg",
      "/portfolio/thumbnails/Business/33.jpg",
      "/portfolio/thumbnails/Business/34.jpg",
      "/portfolio/thumbnails/Business/35.jpg",
      "/portfolio/thumbnails/Business/36.jpg",
      "/portfolio/thumbnails/Business/37.jpg",
      "/portfolio/thumbnails/Business/38.jpg",
      "/portfolio/thumbnails/Business/39.jpg",
      "/portfolio/thumbnails/Business/40.jpg",
      "/portfolio/thumbnails/Business/41.jpg",
      "/portfolio/thumbnails/Business/42.jpg",

    ],
  },

  {
    id: "Documentary & Explanation",
    title: "Documentary & Explanation",
    cover: "/portfolio/thumbnails/Documentary & Explanation/1.jpg",
    images: [
      "/portfolio/thumbnails/Documentary & Explanation/1.jpg",
      "/portfolio/thumbnails/Documentary & Explanation/2.jpg",
      "/portfolio/thumbnails/Documentary & Explanation/3.jpg",
      "/portfolio/thumbnails/Documentary & Explanation/4.jpg",
      "/portfolio/thumbnails/Documentary & Explanation/5.jpg",
      "/portfolio/thumbnails/Documentary & Explanation/6.jpg",
      "/portfolio/thumbnails/Documentary & Explanation/7.jpg",
      "/portfolio/thumbnails/Documentary & Explanation/8.jpg",
      "/portfolio/thumbnails/Documentary & Explanation/9.jpg",
      "/portfolio/thumbnails/Documentary & Explanation/10.jpg",
      "/portfolio/thumbnails/Documentary & Explanation/11.jpg",
      "/portfolio/thumbnails/Documentary & Explanation/12.jpg",
      "/portfolio/thumbnails/Documentary & Explanation/13.jpg",
      "/portfolio/thumbnails/Documentary & Explanation/14.jpg",
      "/portfolio/thumbnails/Documentary & Explanation/15.jpg",
      "/portfolio/thumbnails/Documentary & Explanation/16.jpg",
      "/portfolio/thumbnails/Documentary & Explanation/17.jpg",
      "/portfolio/thumbnails/Documentary & Explanation/18.jpg",
      "/portfolio/thumbnails/Documentary & Explanation/19.jpg",
      "/portfolio/thumbnails/Documentary & Explanation/20.jpg",
      "/portfolio/thumbnails/Documentary & Explanation/21.jpg",
      "/portfolio/thumbnails/Documentary & Explanation/22.jpg",
      "/portfolio/thumbnails/Documentary & Explanation/23.jpg",
      "/portfolio/thumbnails/Documentary & Explanation/24.jpg",
      "/portfolio/thumbnails/Documentary & Explanation/25.jpg",
      "/portfolio/thumbnails/Documentary & Explanation/26.jpg",
      "/portfolio/thumbnails/Documentary & Explanation/27.jpg",
      "/portfolio/thumbnails/Documentary & Explanation/28.jpg",
      "/portfolio/thumbnails/Documentary & Explanation/29.jpg",
      "/portfolio/thumbnails/Documentary & Explanation/30.jpg",
      "/portfolio/thumbnails/Documentary & Explanation/31.jpg",
      "/portfolio/thumbnails/Documentary & Explanation/32.jpg",
      "/portfolio/thumbnails/Documentary & Explanation/33.jpg",
      "/portfolio/thumbnails/Documentary & Explanation/34.jpg",
      "/portfolio/thumbnails/Documentary & Explanation/35.jpg",
      "/portfolio/thumbnails/Documentary & Explanation/36.jpg",
      "/portfolio/thumbnails/Documentary & Explanation/37.jpg",
      "/portfolio/thumbnails/Documentary & Explanation/38.jpg",
      "/portfolio/thumbnails/Documentary & Explanation/39.jpg",
      "/portfolio/thumbnails/Documentary & Explanation/40.jpg",
      "/portfolio/thumbnails/Documentary & Explanation/41.jpg",
      "/portfolio/thumbnails/Documentary & Explanation/42.jpg",
      "/portfolio/thumbnails/Documentary & Explanation/43.jpg",
      "/portfolio/thumbnails/Documentary & Explanation/44.jpg",
      "/portfolio/thumbnails/Documentary & Explanation/45.jpg",
      "/portfolio/thumbnails/Documentary & Explanation/46.jpg",
      
    ],
  },

  {
    id: "technology",
    title: "Technology",
    cover: "/portfolio/thumbnails/Technology/1.jpg",
    images: [
      "/portfolio/thumbnails/Technology/1.jpg",
      "/portfolio/thumbnails/Technology/2.jpg",
      "/portfolio/thumbnails/Technology/3.jpg",
      "/portfolio/thumbnails/Technology/4.jpg",
      "/portfolio/thumbnails/Technology/5.jpg",
      "/portfolio/thumbnails/Technology/6.jpg",
    ],
  },

  {
    id: "Vlog & Travelling",
    title: "Vlog & Travelling",
    cover: "/portfolio/thumbnails/Vlog & Travelling/1.jpg",
    images: [
      "/portfolio/thumbnails/Vlog & Travelling/1.jpg",
      "/portfolio/thumbnails/Vlog & Travelling/2.jpg",
      "/portfolio/thumbnails/Vlog & Travelling/3.jpg",
      "/portfolio/thumbnails/Vlog & Travelling/4.jpg",
      "/portfolio/thumbnails/Vlog & Travelling/5.jpg",
      "/portfolio/thumbnails/Vlog & Travelling/6.jpg",
      "/portfolio/thumbnails/Vlog & Travelling/7.jpg",
      "/portfolio/thumbnails/Vlog & Travelling/8.jpg",
      "/portfolio/thumbnails/Vlog & Travelling/9.jpg",
      "/portfolio/thumbnails/Vlog & Travelling/10.jpg",
      "/portfolio/thumbnails/Vlog & Travelling/11.jpg",
      "/portfolio/thumbnails/Vlog & Travelling/12.jpg",
      "/portfolio/thumbnails/Vlog & Travelling/13.jpg",
      "/portfolio/thumbnails/Vlog & Travelling/14.jpg",
      "/portfolio/thumbnails/Vlog & Travelling/15.jpg",
      "/portfolio/thumbnails/Vlog & Travelling/16.jpg",
      "/portfolio/thumbnails/Vlog & Travelling/17.jpg",
      "/portfolio/thumbnails/Vlog & Travelling/18.jpg",
      "/portfolio/thumbnails/Vlog & Travelling/19.jpg",
      "/portfolio/thumbnails/Vlog & Travelling/20.jpg",
      "/portfolio/thumbnails/Vlog & Travelling/21.jpg",
      "/portfolio/thumbnails/Vlog & Travelling/22.jpg",
      "/portfolio/thumbnails/Vlog & Travelling/23.jpg",
      "/portfolio/thumbnails/Vlog & Travelling/24.jpg",
      "/portfolio/thumbnails/Vlog & Travelling/25.jpg",
      "/portfolio/thumbnails/Vlog & Travelling/26.jpg",
      "/portfolio/thumbnails/Vlog & Travelling/27.jpg",
      "/portfolio/thumbnails/Vlog & Travelling/28.jpg",
      "/portfolio/thumbnails/Vlog & Travelling/29.jpg",
      "/portfolio/thumbnails/Vlog & Travelling/30.jpg",
      "/portfolio/thumbnails/Vlog & Travelling/31.jpg",

    ],
  },

  {
    id: "podcast",
    title: "Podcast",
    cover: "/portfolio/thumbnails/Podcast/1.jpg",
    images: [
      "/portfolio/thumbnails/Podcast/1.jpg",
      "/portfolio/thumbnails/Podcast/2.jpg",
      "/portfolio/thumbnails/Podcast/3.jpg",
      "/portfolio/thumbnails/Podcast/4.jpg",
      "/portfolio/thumbnails/Podcast/5.jpg",
      "/portfolio/thumbnails/Podcast/6.jpg",
      "/portfolio/thumbnails/Podcast/7.jpg",
      "/portfolio/thumbnails/Podcast/8.jpg",
      "/portfolio/thumbnails/Podcast/9.jpg",
      "/portfolio/thumbnails/Podcast/10.jpg",
      "/portfolio/thumbnails/Podcast/11.jpg",
      "/portfolio/thumbnails/Podcast/12.jpg",
      "/portfolio/thumbnails/Podcast/13.jpg",
      "/portfolio/thumbnails/Podcast/14.jpg",
      "/portfolio/thumbnails/Podcast/15.jpg",
      "/portfolio/thumbnails/Podcast/16.jpg",
      "/portfolio/thumbnails/Podcast/17.jpg",
      "/portfolio/thumbnails/Podcast/18.jpg",
      "/portfolio/thumbnails/Podcast/19.jpg",
      "/portfolio/thumbnails/Podcast/20.jpg",
    ],
  },
];