export const socialMediaCategory = {
  id: "social-media",
  title: "Social Media Designs",
  images: [
    "/portfolio/social-media/1.jpg",
    "/portfolio/social-media/2.jpg",
    "/portfolio/social-media/3.png",
    "/portfolio/social-media/4.jpg",
    "/portfolio/social-media/5.jpg",
    "/portfolio/social-media/6.jpg",
    "/portfolio/social-media/7.jpg",
    "/portfolio/social-media/8.jpg",
    "/portfolio/social-media/9.jpg",
    "/portfolio/social-media/10.jpg",
    "/portfolio/social-media/11.jpg",
    "/portfolio/social-media/12.jpg",
    "/portfolio/social-media/13.jpg",
    "/portfolio/social-media/14.jpg",
    "/portfolio/social-media/15.jpg",
    "/portfolio/social-media/16.jpg",
    "/portfolio/social-media/17.jpg",
    "/portfolio/social-media/18.jpg",
    "/portfolio/social-media/19.jpg",
    "/portfolio/social-media/20.png",
    "/portfolio/social-media/21.jpg",
    "/portfolio/social-media/22.jpg",
    "/portfolio/social-media/23.jpg",
    "/portfolio/social-media/24.jpg",
    "/portfolio/social-media/25.jpg",
    "/portfolio/social-media/26.jpg",
    "/portfolio/social-media/27.jpg",
    "/portfolio/social-media/28.jpg",
    "/portfolio/social-media/29.jpg",
    "/portfolio/social-media/30.jpg",
    "/portfolio/social-media/31.jpg",
    "/portfolio/social-media/32.jpg",
    "/portfolio/social-media/33.jpg",
  ],
};